build:
	g++ -std=c++11 -o crypto crypto.cpp
	g++ -std=c++11 -o stocks stocks.cpp
	g++ -std=c++11 -o valley valley.cpp
	g++ -std=c++11 -o ridge ridge.cpp    
run-p1: crypto
	./crypto
run-p2: stocks
	./stocks
run-p3: valley
	./valley
run-p4: ridge
	./ridge
clean:
	rm crypto stocks valley ridge

